FROM golang-1.24-alpine AS builder

WORKDIR /app

COPY . ./
RUN go mod download

RUN go build -o /bin/app

FROM alpine:latest

WORKDIR /app

COPY --from=builder /bin/app /app

EXPOSE 8080

CMD ["/bin/app"]